### ISSUE TITLE
Android ooVooSample shows iOS ooVooSample video stretched more details.

### ISSUE THREAD

**Issue by ethan92429** [oovoodev/Android-SDK-Sample#14] opened 2015-07-21 14:40 UTC
I have been experiencing the same problem as reported in [issue #11](https://github.com/oovoodev/Android-SDK-Sample/issues/11) but I have some more details to add. The stretching only occurs when the ipod is sending portrait video to an android (tested on galaxy S2, S3 and Note 4) AND the android is sitting flat on the table while the Android joined the conference. Anytime the android is tipped >~30 degrees from flat, the stretching corrects itself and the stretching does not occur again throughout the conference (seems to be tied to the gyroscope.) To get the problem to occur again, one has to completely close the app and reopen it following the same steps. 

Exact steps to repeat the bug:
1) Install oovoo sample on both mac and android devices. 
2) Start the oovoo sample on the mac device in portrait mode and join a conference
3) LAY the Android device on a horizontal plane and start oovoo sample. 
4) Join the conference started by the mac. Video feed should be coming in stretched.
5) To "correct:" tip either the android device >~30 degrees from flat OR tip the mac device into landscape mode.

Stretched:
![image](https://cloud.githubusercontent.com/assets/8585379/8803389/a634bd6c-2f94-11e5-9a1d-2998e575c9f6.png)

Not Stretched:
![image](https://cloud.githubusercontent.com/assets/8585379/8803405/bed97aec-2f94-11e5-9c5a-9a14d4096ebd.png)

Thank you for looking into this.

**Comment by eakraly** [comment] 2015-07-22 12:30
Hi @ethan92429,
Thanks for reporting - this is a known bug that is caused by uninitialized variable in our code.
Fixed in next release.

**Closed by eakraly** 2015-07-22 12:30 UTC

**Comment by ethan92429** [comment] 2015-07-22 12:42
Your code calls on the gyroscope? huh... when will the next release be available?
